### ISSUE TITLE
Load of module and client extremely slow.

### ISSUE THREAD

**Issue by Tibiritabara** [mirumee/ariadne-codegen#233] opened 2023-11-03 15:19 UTC
## Description

I have a fairly complex GraphQL repository running on Hasura, that might have hundreds if not thousands of types and definitions. Right now I implemented this library for some specific queries and use cases, and all of those types available in the server are not needed for the execution of my isolated use case.

The generated code, creates a `__init__.py` file where everything is imported on package load. This `__init__.py` file is easily 4k lines of code, generating thousands of imports. Loading the `client` module might easily take minutes and GBs of RAM due to this reason. So I went ahead and deleted everything from the `__init__.py` and left it empty, as the calls to the right types happen on a module by module basis. This reduced my loading time from minutes to miliseconds, and the application still works as expected.

Now the question: is there a reason to import absolutely everything on the `__init__.py`?  For big and complex schemas is an overkill, and increases the application loading time by minutes. Should this file be empty and do a module by module import? - if that is the case, is this not already happening in the current implementation?

Maybe I am missing something, and I greatly appreciate your time and consideration.

**Comment by rafalp** [comment] 2023-11-03 17:03
> Now the question: is there a reason to import absolutely everything on the __init__.py?

Why not? It gives you single place to check for the "public API" and import types from to reuse in your Python logic.

The fairer question to ask would be why didn't we plan for people who have 9000 types in schema and the honest answer is that its hard to predict the extreme without finding it out first.

There's also #226 which points out slow initialization with many types. Are you able to check on your side if this issue is actually a duplicate of it?

Thanks!

**Comment by Tibiritabara** [comment] 2023-11-06 09:36
Thank you so much for your answer and time. I deleted the contents of the `__init__.py` to avoid loading all of those dependencies on runtime, and the project is working as expected. In contrast with #226 my suggestion is to remove the imports completely, rather to just avoid the model rebuild. Would that seem another path to solve this issue?.

Once again, thank you so much for your help and support.

**Comment by bombsimon** [comment] 2024-03-06 10:10
@Tibiritabara are you still running this fine after the introduction of `NoReimportsPlugin`? How many queries, mutations and types do you have?

I'm trying to speed up our implementation but I'm not sure where to focus. We're now at ~220 client methods and ~200 types which results in 220 Python files and a `client.py` at ~28k LOC. Since the client imports all types it doesn't matter that we removed all re-exports from `__init__.py`, just loading the client (which we always need to do) is slow.

```python
>>> def load():
...     now = time.time()
...     import graphql_client.client
...     print(f"took {time.time() - now}")
...
>>> load()
took 4.641252040863037
```

Looking at the output from `python -X importtime -c "from graphql_client.client import Client` mostly just shows that we do all the 200 imports and that we average around 25ms per file. Which I don't know if it's slow. For some files I think it makes sense, a few of them are > 1000 LOC and does ~35 calls to `model_rebuild` (with `0.13.0` that should only do the necessary calls).

We use quite a lot of interfaces and interface implementations so we end up having to import quite a few types and also calling `model_rebuild` on a lot of them. In total we have ~650 calls to `model_rebuild`.

Given that the generator produces one file per method and one class per input and output I'm not sure I can keep my current structure but move it around to decrease load times.

@rafalp Given your previous comment, would you say that 200 queries/mutations and 200 types (including both input and output) would count as an extreme or is this a size you think would be resonable to support?

Is this expected with the current size of our setup? Would us using interfaces be a bad thing and something to try to avoid? Any other pointers on how to re-structure this to improve speed?

**Comment by rafalp** [comment] 2024-03-06 10:19
I have no idea how this question relates to my previous comment in this thread, and I have no experience with clients of this scale to share any insight.

Looks like we should break large clients into namespaces we would lazy load on need, eg.

`client.users.getUser` would call `users` cached property which would include `users_client.py` module, do `UsersClient(self)` with initialization and return this instance.

Alternatively maybe imports should be moved into generated client methods?

**Comment by Tibiritabara** [comment] 2024-03-06 10:48
To be honest, I am still going through the same issue. In this case the imports are not in the `__init__.py` and well that helps, but whenever I import the `Client`, and the `Client` calls the `input_types` everything slows down once again, because `input_types` abundant set of Pydantic models need to be loaded. 

This is a (Pydantic issue)[https://github.com/pydantic/pydantic/discussions/6748] off course, but it could be avoided in this case by encapsulating input types in a query by query basis. Having everything under the same module is really expensive.

**Comment by bombsimon** [comment] 2024-03-06 12:36
> I have no idea how this question relates to my previous comment in this thread

Sorry for unclear ping, I was thinking about the comment "The fairer question to ask would be why didn't we plan for people who have 9000 types in schema and the honest answer is that its hard to predict the extreme without finding it out first." 

My question was if you consider the size of the setup I described as extreme or not, meaning if it's something that's been tested by you or someone else or if it's something that sounds resonable to support.

> Alternatively maybe imports should be moved into generated client methods? This may be achievable with a plugin and should provide some insight on possible speedups.

This sounds like a good idea and would ensure we only load the classes as they're needed. I guess we would also have to convert input types and return types to string literals instead of actual classes, I'll investigate the plugin interface to see if this is doable.

@Tibiritabara Ah, glad to hear it's not just us then. This would also explain why the biggest bump in slowness came from when we upgraded to Pydantic v2.

Does it make sense to re-open this issue or create a new one to track this? It feels like a big enough issue with a not super big setup to track.

**Comment by bombsimon** [comment] 2024-03-13 08:21
I spent some time on this this week and I have a plugin I got working to only import during `TYPE_CHECKING` and in each method. However when combining it with other plugins such as `ShorterResultsPlugin` it no longer works. Reason being that the plugin I wrote is based on collecting resources in different plugin steps such as `generate_client_method` but the plugin `ShorterResultsPlugin` will manipulate the class methods and the global scope with imports in `generate_client_module` which happens way later.

I can see a few ways around this

* Try to make `ShorterResultsPlug` change the ast in earlier steps. Probably not likely since we ended up here with a lot of help from @mat-sop 
* Make my new plugin do all the rewrite logic in `generate_client_method` so no matter if a different plugin has changed the ast we would have the final version in this step
* Put my new plugin first and then also re-write `ShoterResultsPlugin` to do similar changes. I'm not a fan of this because this means that `ShorterResultsPlugin` would have two responsibilities. One to change return type and return call and another to find potential `if TYPE_CHECKING` blocks and put imorts there, or if not create the block.
* Currently the plugin system works by calling each plugin method in order for each plugin rather than calling all the methods for one plugin before the next. It doesn't seem like we could easily change this given the current design but might be worth considering an updated or alternative way of calling plugins.

**Comment by bombsimon** [comment] 2024-03-13 11:03
I rewrote the plugin to just do it all in `generate_client_module`. It's a bit hacky (inefficient with multiple loops) but hopefully you don't generate a client too often. This is my setup now:

Without plugin:

```python
>>> import time
>>> def load():
...     now = time.time()
...     import graphql_client.client
...     print(f"took {time.time() - now}")
...
>>> load()
took 4.913705348968506
```

With plugin:

```python
>>> import time
>>> def load():
...     now = time.time()
...     import graphql_client.client
...     print(f"took {time.time() - now}")
...
>>> load()
took 0.29310107231140137
```

So pretty significant improvement. I'm mainly been testing it together with `ShorterResutlsPlugin` because we need that but should work just as well without that plugin.

My only issue that persists is that the `fix_code` call here here doesn't work anymore. https://github.com/mirumee/ariadne-codegen/blob/c14dd923b8faf960d9c0f6330e5b9c1700354d8e/ariadne_codegen/utils.py#L29-L30

For some reason the fixer doesn't remove unused imports anymore even in the global scope, things not related to my plugin. After I've generated the plugin and run it through the fixer without removing unused imports I have a bunch from `.base_model`:

```python
>>> code = Path("shorter_results/client.py").read_text()
>>> print("\n".join(fix_code(code, remove_all_unused_imports=False).split("\n")[:4]))
from typing import TYPE_CHECKING, Any, AsyncIterator, Dict, List, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType, Upload
```

If I just run the same code as `ast_to_str` and set it to true it's dropped:

```python
>>> print("\n".join(fix_code(code, remove_all_unused_imports=True).split("\n")[:4]))
from typing import TYPE_CHECKING, Any, AsyncIterator, Dict, List, Optional, Union

from .async_base_client import AsyncBaseClient
from .subscribe_strings import SubscribeStrings
```

I'll make sure to share the plugin either in a comment or as a `contrib` PR when I get this last bits working.

**Closed** 2024-04-05 08:44 UTC

**Comment by bombsimon** [comment] 2024-04-07 19:51
Thanks for this! I will give this a go and would love to hear about @Tibiritabara's result as well!

This did speed up our code a lot! However it's also used in a CLI tool of ours which re-creates the client on each invocation. This still being at around ~1.5s doesn't give the best UX. It seems like this is purely due to Pydantic V2 and I'm following the issue linked above with my fingers crossed.

I don't think there's much more we can do with the generated code for now as long as it's using Pydantic. I'll let you know if I find anything of interest that we can try!

**Comment by Tibiritabara** [comment] 2024-04-09 06:53
Thanks for the update and for the amazing work. I am deeply grateful. Currently I am going through other priorities, but soon I will come back to this and try the plugin, and I will update you all with my results.

**Comment by acgourley** [comment] 2024-09-15 19:08
Thanks for your work on this. My hasura endpoint creates a client that takes 11 seconds to load. The ClientForwardRefsPlugin seems to defer this time until the client is built, instead of the cost occuring at the first import, but it doesn't reduce is. Is there anyway to reduce this time? 

I'm only using a small fraction of the hasura endpoint schema I wonder if some filter could be applied to not generate the client for much of it?

**Comment by bombsimon** [comment] 2024-09-15 21:47
> instead of the cost occuring at the first import

That's interesting and not expected but I guess it depends on the schema and general setup. I'm not familiar with Hasura so don't know what's expected. However, the global includes _only_ hapens during type checking, the actual imports only happens within the scope of a single method. The idea here is that you'd only load a subset of what's needed for every client call so in your case that would be one import per client method and that shouldn't take 11 seconds. Do you have an example on how to create such client or a repository where it's published?

> I'm only using a small fraction of the hasura endpoint schema I wonder if some filter could be applied to not generate the client for much of it?

You can always just create your own operations and only define the few queries or mutations you need. If you do that, only those should end up in your GraphQL client. There are a few examples in the tests, [this one](https://github.com/mirumee/ariadne-codegen/tree/main/tests/main/clients/example) show how to create your own queries.

**Comment by acgourley** [comment] 2024-09-15 22:52
Ah you're right it is still slow on import - it simply moved to another import and this confused me. 

Thanks for the link to the example. I am already defining my own queries, but the generated input_types.py is 4.5k LOC and seems to be what is slow. Do I need to define my own schema for that to be smaller? Right now my schema is pulled directly off the graphql endpoint by ariadne-codegen.

**Comment by bombsimon** [comment] 2024-09-16 06:52
> but the generated input_types.py is 4.5k LOC and seems to be what is slow

Ah sorry, yeah that sounds likely! As soon as an input type is needed and you do `from input_types import X` it will read the whole file. Depending on the setup this will include a lot of calls to `model_rebuild` as well. We have a "big" schema but our `input_types` is only ~1900 LOC with 215 classes and we only have ~55 calls to `model_rebuild`.

I think 11s sounds like a lot for what you describe but of course there are many factors that can cause this. For me on my MacBook Pro loading our input_types takes ~0.33s.

> Do I need to define my own schema for that to be smaller?

That's a workaround at least, but that doesn't sound nice to maintain. But other than that I don't know what else to do than monitoring https://github.com/pydantic/pydantic/discussions/6748.

If you have an easy way to re-create and share your client they'd probably appreciate some feedback to [this thread](https://github.com/pydantic/pydantic/discussions/6748#discussioncomment-10396844). I was planning to do that but got off track and didn't have a great shareable repro.

**Comment by acgourley** [comment] 2024-09-23 06:11
Thanks again for looking at this. First of all 🤦 I was giving you that 11s number in debug mode. It's only 3 seconds in normal mode (although on a top of the line m2). 

Second of all, I've wrapped this generated client into a public repo with a readme [here](https://github.com/acgourley/ariadne-codegen-hasura/tree/main) and I'll post it over on the pydantic thread now.
