### ISSUE TITLE
Multiple failures with a Hasura-generated graphql schema

### ISSUE THREAD

**Issue by ataibarkai** [mirumee/ariadne-codegen#100] opened 2023-03-18 00:34 UTC
This project has a tone of promise. Architecturally it looks far, far better than any other python graphql client out there.

However I'm running into multiple issues when using a [Hasura](https://hasura.io/)-generated graphql schema (attached).
[hasura_schema.garphql.txt](https://github.com/mirumee/ariadne-codegen/files/11007098/hasura_schema.garphql.txt)
[the attachment postfix is `.graphql.txt` - so that GitHub would allow me to upload it. Just remove the `.txt` postfix].

A few problems I've run into:

1. Hasura's root Query type is called `query_root`, not `Query` - but `ariadne-codegen` appears to assume it's always called `Query` and fail otherwise (`no property called "..." on type "Query"`...). The GraphQL spec doesn't seem to require a specific name, so would be great to be able to customize this in ariadne-codegen. **I manually renamed `query_root` to `Query`  (in 2 places in the schema) to proceed.**

2. You get into an infinite recursion loop in `_get_dependant_names`. I didn't look at the codebase in detail to see if this fix fully makes sense, but here's the change I made to the relevant function. **I added `pre_callers` argument to avoid recursive cycles:**

```
def _get_dependant_names(self, name: str, pre_callers: List[str] = []) -> List[str]:
    pre_callers = pre_callers.copy()
    
    if name in pre_callers:
        return []
    
    pre_callers.append(name)
    result = []
    
    for dependency_name in self._dependencies[name]:
        if dependency_name != name:
            result.extend(self._get_dependant_names(dependency_name, pre_callers))
            result.append(dependency_name)
            
    return result
```

3. After fixing those errors I got a new one:
`black.parsing.InvalidInput: Cannot parse: 38:4:     in: Optional[List[bool]] = Field(alias='_in')`. **Gave up here**.

**Comment by mat-sop** [comment] 2023-03-20 10:24
Thank you for reporting all of the issues, I looked into them and have some thoughts:

1. We should handle other names for query/mutation types without specifying them in the config. I created a separate issue for this bug #101 .


2. It Looks like the issue is caused by mutually dependent inputs, eg. 
```gql
input person_entities_bool_exp {
  ...
  person_entity_clips: person_entity_clips_bool_exp
  ...
}
input person_entity_clips_bool_exp {
  ...
  person_entity: person_entities_bool_exp
  ...
}
```
so your fix will work (at least for your schema) but I think it needs further investigation regarding other cases and fields' default values.


3. I think a combination of 2 things causes the problem: 
- Enabled `convert_to_snake_case` converts `_in` into `in` 
- `in` is one of python’s keywords, which is not handled

Imo we could handle fields with names that are taken by python's keywords, eg. by adding `_` at the end.  Also converting to a snake case should leave preexisting `_` at the beginning. @rafalp what do you think?

@ataibarkai for now, disabling conversion to snake case (`convert_to_snake_case = false` in `pyproject.toml`) with your fixes from 1. and 2. should allow you to generate client.

**Comment by nargetdev** [comment] 2023-03-27 22:58
I'm also having a recursion issue on a Dgraph generatedSchema.

[schema.graphql.txt](https://github.com/mirumee/ariadne-codegen/files/11083580/schema.graphql.txt)

**Comment by lowzj** [comment] 2023-04-06 23:29
> ...
> 3. I think a combination of 2 things causes the problem:
> 
> * Enabled `convert_to_snake_case` converts `_in` into `in`
> * `in` is one of python’s keywords, which is not handled
> 
> Imo we could handle fields with names that are taken by python's keywords, eg. by adding `_` at the end. 
> ...

same problem as the point 3 mentioned above, I wrote a plugin to rename fields that have the same name as Python keywords:
```python
class FiledPlugin(Plugin):
    def generate_input_field(
            self,
            field_implementation: ast.AnnAssign,
            input_field: GraphQLInputField,
            field_name: str,
    ) -> ast.AnnAssign:
        if iskeyword(field_implementation.target.id):
            field_implementation.target.id = f'{field_implementation.target.id}_'
            field_implementation.value = self._process_field_value(
                field_implementation=field_implementation, alias=field_name
            )
        return field_implementation

    def _process_field_value(
            self,
            field_implementation: ast.AnnAssign,
            alias: str,
    ) -> ast.Call:
        field_with_alias = generate_field_with_alias(alias)
        if field_implementation.value:
            if (
                    isinstance(field_implementation.value, ast.Call)
                    and isinstance(field_implementation.value.func, ast.Name)
                    and field_implementation.value.func.id == FIELD_CLASS
            ):
                field_with_alias.keywords.extend(field_implementation.value.keywords)
            else:
                field_with_alias.keywords.append(
                    generate_keyword(
                        arg="default",
                        value=field_implementation.value,
                    )
                )
        return field_with_alias
```
I see the great works #113 on this issue, could we provide another plugin entry to make `process_name` customized and easier in all places.

**Comment by mat-sop** [comment] 2023-04-18 10:51
@ataibarkai Fixes to all of these problems are now released, so I'm closing this issue.
@lowzj New plugin hook [process_name](https://github.com/mirumee/ariadne-codegen/blob/main/PLUGINS.md#process_name) has also been released

**Closed by mat-sop** 2023-04-18 10:51 UTC
